// <auto-generated />
using System;
using EcommerceApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcommerceApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260620212849_SistemaPedidosCheckout")]
    partial class SistemaPedidosCheckout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcommerceApp.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comuna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeptoBlockOficina")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("EcommerceApp.Models.PedidoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<int>("PrecioUnitario")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("PedidosDetalle");
                });

            modelBuilder.Entity("EcommerceApp.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Precio")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "16 núcleos y 32 hilos a 5.7GHz. Potencia bruta para renderizado y compilación pesada.",
                            ImagenUrl = "https://i.postimg.cc/m2tRPqgs/Ryzen-7950x.png",
                            Nombre = "AMD Ryzen 9 7950X",
                            Precio = 589990
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descripcion = "Arquitectura híbrida de 24 núcleos. Frecuencia térmica máxima de 6.0 GHz.",
                            ImagenUrl = "https://i.postimg.cc/RCYyD04X/14900k.png",
                            Nombre = "Intel Core i9-14900K",
                            Precio = 619990
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Descripcion = "El rey indiscutido del gaming gracias a su tecnología de caché vertical 3D V-Cache.",
                            ImagenUrl = "https://i.postimg.cc/5jcPN6tW/7800.png",
                            Nombre = "AMD Ryzen 7 7800X3D",
                            Precio = 429990
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descripcion = "20 núcleos avanzados optimizados para streaming, diseño y multitarea pesada.",
                            ImagenUrl = "https://i.postimg.cc/rFxTG4xf/14700k.png",
                            Nombre = "Intel Core i7-14700K",
                            Precio = 449990
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            Descripcion = "Excelente punto de entrada a la plataforma AM5 con soporte nativo PCIe 5.0.",
                            ImagenUrl = "https://i.postimg.cc/rpn2yN2x/7600X.png",
                            Nombre = "AMD Ryzen 5 7600X",
                            Precio = 239990
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 2,
                            Descripcion = "Fuerza bruta para Inteligencia Artificial, trazado de rayos completo y 4K extremo.",
                            ImagenUrl = "https://i.postimg.cc/qMsf6Td4/4090RTX.png",
                            Nombre = "NVIDIA GeForce RTX 4090 24GB",
                            Precio = 1949990
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 2,
                            Descripcion = "Rendimiento puro en rasterización para dominar cualquier juego en monitores ultra-wide.",
                            ImagenUrl = "https://i.postimg.cc/JhdSC7jM/RX7900.png",
                            Nombre = "AMD Radeon RX 7900 XTX 24GB",
                            Precio = 1049990
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 2,
                            Descripcion = "El equilibrio perfecto con arquitectura Ada Lovelace para 1440p a 144Hz estables.",
                            ImagenUrl = "https://i.postimg.cc/xTSh24NX/RTX4070-SUPER.png",
                            Nombre = "NVIDIA GeForce RTX 4070 Ti Super 16GB",
                            Precio = 869990
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 2,
                            Descripcion = "La opción con mejor relación precio-rendimiento del mercado para resoluciones Quad HD.",
                            ImagenUrl = "https://i.postimg.cc/sggnfdjL/RX7800X.png",
                            Nombre = "AMD Radeon RX 7800 XT 16GB",
                            Precio = 549990
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 3,
                            Descripcion = "Kit de alto rendimiento 2x32GB a 6600MHz con disipador térmico de aluminio.",
                            ImagenUrl = "https://i.postimg.cc/26RFZPYf/Corsair-64GB-DDR5.png",
                            Nombre = "Corsair Dominator Titanium 64GB DDR5",
                            Precio = 289990
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 3,
                            Descripcion = "Kit de latencia ultra baja 2x16GB a 6000MHz CL30 optimizado para AMD EXPO.",
                            ImagenUrl = "https://i.postimg.cc/3N9gzNv7/G-Skill-32GB-DDR5.png",
                            Nombre = "G.Skill Trident Z5 Neo RGB 32GB DDR5",
                            Precio = 145990
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 3,
                            Descripcion = "Memoria estable de perfil bajo a 5600MHz, ideal para disipadores de torre masivos.",
                            ImagenUrl = "https://i.postimg.cc/h40bXy3N/Kingston-32GB-DDR5.png",
                            Nombre = "Kingston FURY Beast DDR5 32GB",
                            Precio = 119990
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 3,
                            Descripcion = "Módulo de actualización seguro a 3200MHz con disipador negro integrado de fábrica.",
                            ImagenUrl = "https://i.postimg.cc/6qBrHnTp/Crucial-16GB-DDR4.png",
                            Nombre = "Crucial Pro RAM 16GB DDR4",
                            Precio = 42990
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 4,
                            Descripcion = "Unidad PCIe 4.0 con velocidades de lectura de hasta 7450 MB/s. Cero loading screens.",
                            ImagenUrl = "https://i.postimg.cc/BbZF53wd/Samsung-990-PRO-2TB.png",
                            Nombre = "Samsung 990 PRO 2TB NVMe M.2",
                            Precio = 185990
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 4,
                            Descripcion = "Arquitectura NVMe optimizada con modo de juego predictivo de texturas.",
                            ImagenUrl = "https://i.postimg.cc/vTPV3KJY/WD-Black-1TB.png",
                            Nombre = "WD Black SN850X 1TB SSD NVMe",
                            Precio = 105990
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 4,
                            Descripcion = "Excelente almacenamiento principal para arrancar Windows en 5 segundos.",
                            ImagenUrl = "https://i.postimg.cc/jqvPxWL1/Crucial-P3-500GB.png",
                            Nombre = "Crucial P3 Plus 500GB PCIe 4.0",
                            Precio = 54990
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 4,
                            Descripcion = "Placa base entusiasta con fases de poder 18+2, ranuras PCIe 5.0 y puertos duales USB4.",
                            ImagenUrl = "https://i.postimg.cc/3JVyN2YH/ASUS-ROG-X670E.png",
                            Nombre = "ASUS ROG Crosshair X670E Hero",
                            Precio = 649990
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 4,
                            Descripcion = "Estructura blindada con disipación Shield Frozr, soporte DDR5 y Wi-Fi 6E.",
                            ImagenUrl = "https://i.postimg.cc/cJM6Fj3B/MSI-MAG-B650.png",
                            Nombre = "MSI MAG B650 Tomahawk WiFi",
                            Precio = 229990
                        },
                        new
                        {
                            Id = 19,
                            CategoriaId = 4,
                            Descripcion = "Fuente modular ATX 3.0 con certificación 80 Plus Gold y cable nativo PCIe 5.0.",
                            ImagenUrl = "https://i.postimg.cc/XJjqm8cC/Seasonic-1000W.png",
                            Nombre = "Seasonic Vertex GX-1000 1000W",
                            Precio = 215990
                        },
                        new
                        {
                            Id = 20,
                            CategoriaId = 4,
                            Descripcion = "Pasta térmica premium de alta conductividad para un control térmico absoluto.",
                            ImagenUrl = "https://i.postimg.cc/G2XtCyq5/Pasta-Kryonaut.png",
                            Nombre = "Thermal Grizzly Kryonaut Extreme",
                            Precio = 19990
                        });
                });

            modelBuilder.Entity("EcommerceApp.Models.SolicitudVip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoProyecto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SolicitudesVip");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EcommerceApp.Models.PedidoDetalle", b =>
                {
                    b.HasOne("EcommerceApp.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceApp.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcommerceApp.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
